server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: notification-microservice

  datasource:
    url: ${NOTIFICATION_DB_URL}
    username: ${NOTIFICATION_DB_USER}
    password: ${NOTIFICATION_DB_PASSWORD}

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

kafka:
  topics:
    sending-notification-topic: "sending_notification_topic"
    sending-notification-result-topic: "sending_notification_result_topic"
  groups:
    bs-group: "bs-kafka-group"
