server:
  lifecycle.timeout-per-shutdown-phase: 20s
  shutdown: graceful
  port: ${GATEWAY_SERVER_PORT:8083}

management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

bookstatistic:
  routing:
    analyze: http://localhost:8085
    book: http://localhost:8082
    notification: http://localhost:8081
    gateway: http://localhost:8083
    keycloak: http://localhost:8080
    account: http://localhost:8084

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookstatistic
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic-realm}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    discovery.locator:
      enabled: true
      lowerCaseServiceId: true
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/notifications/**
          filters:
            - RewritePath=/notification-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/v1/books/**
          filters:
            - RewritePath=/book-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**
          filters:
            - RewritePath=/account-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: analyze-service
          uri: lb://analyze-service
          predicates:
            - Path=/v1/analyze/**
          filters:
            - RewritePath=/analyze-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

keycloak:
  client-id: bookstatistic
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: bookstatistic-realm
    client-id: bookstatistic
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm: bookstatistic-realm
  auth-server-url: ${KEYCLOAK_AUTH_URL:http://localhost:8080}
  resource: bookstatistic
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  bearer-only: true
  use-resource-role-mappings: true
  init:
    enabled: false