server:
  port: ${GATEWAY_SERVER_PORT:8083}

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    discovery.locator:
      enabled: true
      lowerCaseServiceId: true
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/notification-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          filters:
            - RewritePath=/book-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**
          filters:
            - RewritePath=/account-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: analyze-service
          uri: lb://analyze-service
          predicates:
            - Path=/api/v1/analyze/**
          filters:
            - RewritePath=/analyze-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie