input {
    tcp {
        port => 8085
        codec => json_lines
        type => "java-app"
    }
}

filter {
    # Парсим timestamp из лога
        date {
            match => ["timestamp", "ISO8601"]
            target => "@timestamp"
        }

        # Добавляем информацию об окружении
        mutate {
            add_field => {
                "environment" => "production"
                "app_name" => "my-java-app"
            }
        }

        # Удаляем ненужные поля
        mutate {
            remove_field => ["host", "port"]
        }

        # Извлекаем уровень логирования
        grok {
            match => { "message" => "%{LOGLEVEL:log_level}" }
        }
}

output {
    stdout {
        codec => rubydebug
    }
}