server:
  port: ${ANALYZE_SERVER_PORT:8085}

ml:
  model:
    path: classpath:models/sbert_base.onnx
  vocab:
    path: classpath:models/vocab.txt
  classifier:
    path: classpath:models/genre_classifier_dl4j.zip

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

spring:
  zipkin.baseUrl: zipkin:9411
  sleuth.sampler.percentage: 1

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: bs-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: analyze-service

  datasource:
    url: ${ANALYZE_PG_DB_URL:jdbc:postgresql://localhost:5452/analyze_pgsql_db}
    username: ${ANALYZE_PG_DB_USER}
    password: ${ANALYZE_PG_DB_PASSWORD}

  redis:
    host: localhost
    port: 6378
    password:
    database: 0
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

servlet:
  multipart:
    max-file-size: 30MB
    max-request-size: 30MB
    enabled: true

external-urls:
  account:
    base-url: "http://localhost:8084/v1/users"
    get-account-uri: "/"
  book:
    book-base-url: "http://localhost:8082/v1/books"
    get-users-book-uri: "/user/"
    response-base-url: "http://localhost:8082/v1/responses"
    get-users-responses-uri: "/users/"

keycloak:
  realm: bookstatistic-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: bookstatistic # идентификатор клиента
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  bearer-only: true
  use-resource-role-mappings: true

kafka:
  topics:
    book-text-analyze-topic: "book-text-analyze-topic"
    book-text-analyze-result-topic: "book-text-analyze-result-topic"
  groups:
    bs-group: "bs-group"