FROM eclipse-temurin:21-jdk-alpine as build

# Устанавливаем Maven в контейнере
RUN apk add --no-cache maven

WORKDIR /app

COPY . .

# Используем mvn напрямую (без mvnw)
RUN mvn clean package -DskipTests -pl gateway -am -e

FROM eclipse-temurin:21-jre-alpine

VOLUME /tmp

COPY --from=build /app/gateway/target/*.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]