apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: bookstatistic
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: analyze_mongodb_username
  MONGO_INITDB_ROOT_PASSWORD: analyze_mongodb_password
  MONGO_INITDB_DATABASE: bookstatistic-analyze
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-book
  namespace: bookstatistic
spec:
  selector:
    app: mongodb-book
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-analyze
  namespace: bookstatistic
spec:
  serviceName: mongodb-analyze
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-analyze
  template:
    metadata:
      labels:
        app: mongodb-analyze
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27018
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_DATABASE
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-analyze-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-analyze-pvc
  namespace: bookstatistic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi