external-urls:
  notification:
    base-url: http://localhost:8081/
    add-new-notification:

server:
  lifecycle.timeout-per-shutdown-phase: 20s
  shutdown: graceful
  port: ${BOOK_SERVER_PORT}

book:
  storage:
    path: ${BOOK_STORAGE_PATH}
    max-file-size: 104857600
    allowed-extensions:
      - .txt
      - .pdf
      - .epub
      - .fb2
      - .docx

management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

spring:
  data:
    mongodb:
      port: ${BOOK_MONGO_DB_PORT}
      username: ${BOOK_MONGO_DB_USERNAME}
      password: ${BOOK_MONGO_DB_PASSWORD}
      database: ${BOOK_MONGO_DB_NAME:bookstatistic}
      authentication-database: admin

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true

  application:
    name: book-service

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: bs-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: ${BOOK_PG_DB_URL}
    username: ${BOOK_PG_DB_USER}
    password: ${BOOK_PG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  zipkin:
    baseUrl: zipkin:9411

  sleuth:
    sampler:
      percentage: 1

keycloak:
  realm: bookstatistic-realm
  auth-server-url: http://keycloak:8090/auth
  ssl-required: external
  resource: bookstatistic
  credentials:
    secret:
  bearer-only: true
  use-resource-role-mappings: true

kafka:
  topics:
    sending-notification-topic: "sending-notification-topic"
    sending-notification-result-topic: "sending-notification-result-topic"
    book-text-analyze-topic: "book-text-analyze-topic"
  groups:
    bs-group: "bs-group"

outbox:
  enabled: true