eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

zipkin.baseUrl: zipkin:9411
spring.sleuth.sampler.percentage: 1

external-url:
  notification:
    base-url: http://localhost:8081/
    add-new-notification:

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

spring:
  application:
    name: book-service

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true

logging:
  level:
  org.springframework.web: WARN
  org.jedi_bachelor.bookstatistic: DEBUG

keycloak:
  realm: bookstatistic-realm
  auth-server-url: http://keycloak:8090/auth
  ssl-required: external
  resource: bookstatistic # идентификатор клиента
  credentials:
    secret: # здесь должен быть secret key из панели keycloak
  bearer-only: true
  use-resource-role-mappings: true