external-url:
  notification:
    base-url: http://localhost:8081/
    add-new-notification:

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

spring:
  application:
    name: book-service