spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sleuth:
    sampler:
      probability: 1.0
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookstatistic
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic-realm}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic-realm}

  application:
    name: account-service

  datasource:
    url: ${ACCOUNT_DB_URL:jdbc:postgresql://localhost:5432/account_db}
    username: ${ACCOUNT_DB_USER:postgres}
    password: ${ACCOUNT_DB_PASSWORD:postgres}

external-urls:
  analyze:
    base-url: ${ANALYZE_SERVICE_URL:http://localhost:8083/v1/analyze}
    delete-user-data: /
  notification:
    base-url: http://localhost:8083/v1/notifications
    post-notification-settings: /notification-settings

server:
  port: ${ACCOUNT_SERVER_PORT:8084}

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

keycloak:
  client-id: bookstatistic
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: bookstatistic-realm
    client-id: bookstatistic
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm: bookstatistic-realm
  auth-server-url: ${KEYCLOAK_AUTH_URL:http://localhost:8080}
  resource: bookstatistic
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  bearer-only: true
  use-resource-role-mappings: true
  init:
    enabled: false

zipkin:
  baseUrl: ${ZIPKIN_URL:http://zipkin:9411}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

kafka:
  topics:
    sending-notification-topic: "sending-notification-topic"
    sending-notification-result-topic: "sending-notification-result-topic"
  groups:
    bs-group: "bs-group"