spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookstatistic-app
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid,profile,email,roles
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic}
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bookstatistic}/protocol/openid-connect/certs
  application:
    name: account-service

  datasource:
    url: ${ACCOUNT_DB_URL}
    username: ${ACCOUNT_DB_USER}
    password: ${ACCOUNT_DB_PASSWORD}

external-url:
  book: "http://localhost:8082/books"
  analyzer: "http://localhost:8083/analyze"

server:
  port: ${ACCOUNT_SERVER_PORT}

jwt:
  auth-converter:
    principal-claim: preferred_username
    resource-id: bookstatistic-app

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: bookstatistic
    client-id: admin-cli
    client-secret: ${KEYCLOAK_ADMIN_SECRET}

zipkin.baseUrl: zipkin:9411
spring.sleuth.sampler.percentage: 1