apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bookstatistic
type: Opaque
stringData:
  POSTGRES_USER: user_postgres
  POSTGRES_PASSWORD: password_pgsql_db
  POSTGRES_DB: account_pgsql_db
---
apiVersion: v1
kind: Service
metadata:
  name: account-postgres
  namespace: bookstatistic
  labels:
    app: account-postgres
spec:
  selector:
    app: account-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: account-postgres
  namespace: bookstatistic
spec:
  serviceName: account-postgres
  replicas: 1
  selector:
    matchLabels:
      app: account-postgres
  template:
    metadata:
      labels:
        app: account-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: TZ
              value: UTC+3
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: account-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-postgres-pvc
  namespace: bookstatistic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi