@startuml

title Добавление новой книги в систему

actor Администратор as admin
participant Gateway as gateway
participant BookService as bookService
participant AnalyzeService as analyzeService

admin -> gateway : 1. Отправка запроса на создание новой книги
gateway -> bookService : 2. Добавление новой книги
bookService -> analyzeService : 3. Добавление информации по книге
analyzeService -> analyzeService : 4. Сохранение информации
analyzeService -> bookService : 5. Возврат ответа
bookService -> gateway : 6. Возврат ответа
gateway -> admin : 7. Возврат ответа
admin -> gateway : 8. Отправка текста для этой книги
gateway -> bookService : 9. Добавление текстов
bookService -> analyzeService : 10. Добавление текста
analyzeService -> analyzeService : 11. Проведение анализа текста
analyzeService -> analyzeService : 12. Сохранение статической информации по тексту по анализу
analyzeService -> bookService : 13. Возвращение ответа по успешной добавке текста
bookService -> gateway : 14. Возвращение ответа по добавлению книги
gateway -> admin : 15. Возврат ответа

@enduml