@startuml

actor Пользователь as user
participant Gateway as gateway
participant AccountService as accountService
participant Keycloak as keycloak

user -> gateway : 1. Запрос на регистрацию
gateway -> accountService : 2. Передача данных на регистрацию
accountService -> accountService : 3. Сохранение данных / формирование access token-а
accountService -> keycloak : 4. Сохранение пользователя в Keycloak
accountService -> gateway : 5. Передача данных регистрации
gateway -> user : 6. Передача данных регистрации

@enduml