@startuml
title Отправка уведомления пользователю

participant AnalyzeService as analyzeservice
queue sending_notification_topic as notificationservicetopic
queue sending_notification_result_topic as notificationserviceresulttopic
participant NotificationService as notificationservice

analyzeservice -> notificationservicetopic : 1. Отправка данных в топик
notificationservicetopic -> notificationservice : 2. Чтение данных из топика
notificationservice -> notificationservice : 3. Запрос на получение адреса email
notificationservice -> notificationservice : 4. Формирование сообщения для пользователя
notificationservice -> notificationserviceresulttopic : 5. Отправка ответа о результатах формирования сообщения
notificationserviceresulttopic -> analyzeservice : 6. Чтение сообщения о результатах

@enduml