eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  lifecycle.timeout-per-shutdown-phase: 20s
  shutdown: graceful
  port: ${NOTIFICATION_SERVER_PORT:8081}

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: bs-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.jedi_bachelor.bookstatistic.commonslib.dto.request.notification.NotificationCreationDto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1

  application:
    name: notification-service

  datasource:
    url: ${NOTIFICATION_DB_URL}
    username: ${NOTIFICATION_DB_USER}
    password: ${NOTIFICATION_DB_PASSWORD}

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          enable: true
    default-encoding: UTF-8

kafka:
  topics:
    sending-notification-topic: "sending-notification-topic"
    sending-notification-result-topic: "sending-notification-result-topic"
  groups:
    bs-group: "bs-group"

external-urls:
  account:
    base-url: http://localhost:8083/v1/users

management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false
    health:
      enabled: true
      show-details: always
      db:
        enabled: false
      diskspace:
        enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.jedi_bachelor.bookstatistic.notificationservice: DEBUG
    org.springframework.security.oauth2: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      notification-circuitbreaker:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException

  bulkhead:
    instances:
      notification-bulkhead:
        maxWaitDuration: 2ms
        maxConcurrentCalls: 20