name: Bookstatistic Java CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код
      - uses: actions/checkout@v4

      # 2. Устанавливаем JDK (версию под свой проект)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Сборка
      - name: Build with Maven
        run: mvn clean build

      # 4. Тестируем
      - name: Test
        run: mvn clean test